### ISSUE TITLE
Captcha keep moving when typing in form

### ISSUE THREAD

**Issue by kev-is-coding-for-adn** [tossnet/Blazor-Captcha#12]
I use last version of Blazor-Captcha on .NET 7 application.

I have a login form with 2 TextField and the captcha.
For every character that I type in the different textfields, the captcha is "moving" : it has the same characters but the "lines" and the characters change their positions slightly.
It is very annoying and very uncomfortable.
Can you help ?

**Comment by kev-is-coding-for-adn** [comment]
It seems to be relative to the use of "MudForm", a component from MudBlazor library. But I don't know yet what I can do to prevent this.

**Comment by ajahangard** [comment]
@kev-is-coding-for-adn 
I had the same problem in the login form. I was capturing KeyPress event on the form so the captcha refreshed on every key press.
I removed the @onkeypress from the div element and the problem resolved.

**Comment by tossnet** [comment]
The code is open source, don't hesitate to suggest an improvement to solve your problem

**Comment by ajahangard** [comment]
The problem is that image creation logic is in BuildRenderTree method.
I changed the Captcha.cs in the following manner and the problem is resolved:
I created a private img field and moved image creation logic from BuildRenderTree to Initialization:
I created a pull request #16  for this.
@tossnet @kev-is-coding-for-adn

**Comment by tossnet** [comment]
/
